# Generated by Django 2.1.7 on 2019-05-03 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField()),
                ('faculty', models.CharField(choices=[('01', 'วิศวกรรมศาสตร์'), ('02', 'สถาปัตยกรรมศาสตร์'), ('03', 'ครุศาสตร์อุตสาหกรรมและเทคโนโลยี'), ('04', 'เทคโนโลยีการเกษตร'), ('05', 'วิทยาศาสตร์'), ('06', 'อุตสาหกรรมเกษตร'), ('07', 'เทคโนโลยีสารสนเทศ'), ('08', 'วิทยาลัยนานาชาติ'), ('09', 'วิทยาลัยนาโนเทคโนโลยี'), ('10', 'วิทยาลัยนวัตกรรมการผลิตขั้นสูง'), ('11', 'การบริหารและจัดการ'), ('12', 'วิทยาลัยอุตสาหกรรมการบินนานาชาติ'), ('13', 'ศิลปศาสตร์'), ('14', 'แพทยศาสตร์'), ('15', 'วิทยาลัยวิศวกรรมสังคีต')], default='01', max_length=2)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('01', 'Male'), ('02', 'Female')], default='01', max_length=2)),
                ('area', models.TextField()),
                ('salary', models.IntegerField(default=0)),
                ('job_type', models.CharField(choices=[('01', 'Part-time'), ('02', 'Internship')], default='01', max_length=2)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobprovider.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobprovider.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('01', 'Male'), ('02', 'Female')], default='01', max_length=2)),
                ('is_unemp', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobprovider.Student'),
        ),
    ]
