# Generated by Django 2.1.7 on 2019-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobprovider', '0002_auto_20190504_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='faculty',
            field=models.CharField(choices=[('01', 'วิศวกรรมศาสตร์'), ('02', 'สถาปัตยกรรมศาสตร์'), ('03', 'ครุศาสตร์อุตสาหกรรมและเทคโนโลยี'), ('04', 'เทคโนโลยีการเกษตร'), ('05', 'วิทยาศาสตร์'), ('06', 'อุตสาหกรรมเกษตร'), ('07', 'เทคโนโลยีสารสนเทศ'), ('08', 'วิทยาลัยนานาชาติ'), ('09', 'วิทยาลัยนาโนเทคโนโลยี'), ('10', 'วิทยาลัยนวัตกรรมการผลิตขั้นสูง'), ('11', 'การบริหารและจัดการ'), ('12', 'วิทยาลัยอุตสาหกรรมการบินนานาชาติ'), ('13', 'ศิลปศาสตร์'), ('14', 'แพทยศาสตร์'), ('15', 'วิทยาลัยวิศวกรรมสังคีต'), ('16', 'Any')], default='03', max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('01', 'Male'), ('02', 'Female'), ('03', 'Any')], default='03', max_length=2),
        ),
    ]
