# Generated by Django 2.1.7 on 2019-05-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobprovider', '0003_auto_20190505_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobprovider.Job')),
            ],
        ),
    ]
